import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./securemeet.db")
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY")
JWT_ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("JWT_ACCESS_TOKEN_EXPIRE_MINUTES", 60))
ROOM_DEFAULT_DURATION_HOURS = int(os.getenv("ROOM_DEFAULT_DURATION_HOURS", 2))
JWT_ROOM_TOKEN_EXPIRE_MINUTES = int(os.getenv("JWT_ROOM_TOKEN_EXPIRE_MINUTES", ROOM_DEFAULT_DURATION_HOURS * 60))
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
